### ISSUE TITLE
dbt fabric connector v1.9.1: compilation error on models with contract enforcement

### ISSUE THREAD

**Issue by jannickvangiel** [microsoft/dbt-fabric#263]
Below compilation error is occurring since version 1.9.1.
Works as expected in prior versions.

`As contract is enforced and the model is using CTE, INSERT INTO is not supported with CTE. Either do not enforce contract or change the model`

```
  > in macro fabric__create_table_as (macros\materializations\models\table\create_table_as.sql)
  > called by macro create_table_as (macros\relations\table\create.sql)
  > called by macro statement (macros\etc\statement.sql)
  > called by macro materialization_table_fabric (macros\materializations\models\table\table.sql)
  > called by model azure_sql_xxxx (models\01_bronze\azure_sql_xxx\azure_sql_xxx.sql)
```

**Comment by arasdk** [comment]
We are getting the same breaking change on all our public models with contract enforced in our environment with 1.9.1. Works fine with 1.9.0.

**Comment by jannickvangiel** [comment]
> We are getting the same breaking change on all our public models with contract enforced in our environment with 1.9.1. Works fine with 1.9.0.

Thanks for the confirmation.

**Comment by prdpsvs** [comment]
There is a hotfix rolling out tomorrow. The issue was that table materialization is checking for CTE usage with contract. The check must be for nested CTE's but not regular CTE.

I made a change to detect if model contains nested cte.

If the contract is enforced and the model contains a nested CTE, Fabric DW uses CREATE TABLE + INSERT to load data. INSERT INTO is not supported with nested CTEs. To resolve this, either disable contract enforcement or modify the model.

I might yank 1.9.1 once I release 1.9.2
